// To execute Go code, please declare a func main() in a package "main"

package stockprices

/*

Stock Analysis:
Imagine that you are a stock analyst, and you are tasked with doing some historical analysis of one particular stock. Specifically, you are provided with some time-series data representing the price of the stock on each day for a period of N consecutive days. For example, let’s say you are given a week’s worth of data as follows:
  stockPrices = [ 150.55, 112.50, 130.25, 120.25, 145.75, 110.00, 90.90 ] => 33.25

Can you please write some code to calculate the largest sum of money, or return, that will be generated by adhering to the following set of constraints:
The stock *must* be purchased exactly one time
The stock *must* be sold exactly one time
The sale must happen after the point of purchase. That is to say you cannot buy and sell on the same day, and you of course cannot sell before you buy.

*/

//FindBestPrice :
//Space Complexity : constant
// Time Complexity = O(n)
func FindBestPrice(s []float64) float64 {
	if len(s) < 2 {
		return 0
	}
	if len(s) == 2 {
		return (s[1] - s[0])
	}

	lowPrice := s[0]
	//highPrice := s[1]
	maxProfit := s[1] - s[0]
	var diff float64

	for i := 1; i < len(s); i++ {

		diff += s[i] - s[i-1] // increment diff to get profit so far
		if diff > maxProfit {
			maxProfit = diff
			//highPrice = s[i]
		}
		if s[i] < lowPrice { // if current price is lower - reset lowPrice and diff
			lowPrice = s[i]
			diff = 0 /// reset the diff when you find a lower price
		}
	}

	return maxProfit

}

/*
func main() {

	stockPrices := []float64{150.55, 112.50, 130.25, 120.25, 145.75, 110.00, 90.90}

	//stockPrices := []float64{150.55, 120.50, 115.25, 111.25, 90.75, 30.00, 20.90}

	if len(stockPrices) <= 1 {
		fmt.Println("Error")
		os.Exit(1)
	}
	fmt.Println(FindBestPrice(stockPrices))
}
*/
